### PR TITLE
stdlib: use unsigned arithmetic in rand() to fix overflow

### LINKED ISSUE #988: random.c: Signed integer overflow when using sanitizers
```c
NEWLIB_THREAD_LOCAL long long _rand_next = 1;

long int
random (void)
{
  /* This multiplier was obtained from Knuth, D.E., "The Art of
     Computer Programming," Vol 2, Seminumerical Algorithms, Third
     Edition, Addison-Wesley, 1998, p. 106 (line 26) & p. 108 */
  _rand_next = _rand_next * __extension__ 6364136223846793005LL + 1;
  return (long int)((_rand_next >> 32) & RAND_MAX);
}
```

Currently the above function (in libc/stdlib/random.c) can trigger Clang's undefined behavior sanitizer as in the following example: `signed integer overflow: 6364136223846793006 * 6364136223846793005 cannot be represented in type 'long long'`.

### PR DESCRIPTION
**Pull request by GalaxyShard**
Closes #988

I checked newlib's source code and found that they use `unsigned long long`, which is what I changed the previous `long long` to here.

### CODE REVIEW

File: newlib/libc/stdlib/random.c [hunk 1]
```diff
@@ -55,14 +55,14 @@ algorithm as <<rand>>.
 #define _DEFAULT_SOURCE
 #include <stdlib.h>
 
-__THREAD_LOCAL long long _rand_next = 1;
+__THREAD_LOCAL unsigned long long _rand_next = 1;
```
Comment (keith-packard) [inline newlib/libc/stdlib/random.c:58]: This looks good, but we should make this actually match what's in taocp and use uint64_t instead of 'unsigned long long', which might not be 64 bits.

**Review by keith-packard — APPROVED** [review]

**Comment by GalaxyShard** [comment]
Forgot to include the right header, sorry about that!

File: newlib/libc/stdlib/random.c [hunk 2]
```diff
@@ -54,15 +54,16 @@ algorithm as <<rand>>.
...
+__THREAD_LOCAL uint64_t _rand_next = 1;
 
 long int
 random (void)
 {
   /* This multiplier was obtained from Knuth, D.E., "The Art of
      Computer Programming," Vol 2, Seminumerical Algorithms, Third
      Edition, Addison-Wesley, 1998, p. 106 (line 26) & p. 108 */
-  _rand_next = _rand_next * __extension__ 6364136223846793005LL + 1;
+  _rand_next = _rand_next * __extension__ 6364136223846793005ULL + 1;
```
Comment (jserv) [inline newlib/libc/stdlib/random.c:67]: Is it necessary to add `__extension__` since modern C compilers should handle `ULL` fine?

Comment (keith-packard) [reply newlib/libc/stdlib/random.c:67]: yeah, long long was in C99. Feel free to remove that.
